### ISSUE TITLE
Ability to capture the current line number value

### ISSUE THREAD

**Issue by soticoker** [spslater/obsidian-cursor-location-plugin#5] opened 2021-09-11 12:24 UTC
Love this plug-in! Would be great to be able to use this plug-in to capture the current line number.  perhaps being able to *assign a hotkey* and copy to clipboard or being able to paste the line number value in the 'go to line' function text box.  

I use voice recognition to write my notes I need the current line number value to tell my program which lines to manipulate.

**Comment by spslater** [comment] 2021-09-12 13:29
I like this idea! I will start working on this soon!

**Comment by spslater** [comment] 2021-09-12 23:56
> being able to paste the line number value in the 'go to line' function text box
Is this an existing function / text box?
Or are you suggesting a new one be added?

What I'm thinking is two new hotkeys:
1. Copy current line number to clipboard
2. Open a "go to line" dialog to go to the provided line
    - Possibly allow adding multiple cursors by passing in a list (either separated by commas, spaces, or both)

**Comment by soticoker** [comment] 2021-09-13 13:41
Hi Sean, 
glad you like the idea !

re "being able to paste the line number value in the 'go to line' function text box", 
it's a built in Obsidian function. The default hotkey is ctrl+g to invoke it.  I suppose for basic functionality maybe use the build in "go to line(ctrl+g )" function but if you wanted to make this function with multiple cursors etc, you'd need to create a new "go to line" function.  I actually don't use multiple cursors so not sure of this functionality.  

Defo love the - Copy current line number to clipboard idea !

thanks

**Comment by spslater** [comment] 2021-09-13 15:43
> it's a built in Obsidian function. The default hotkey is ctrl+g to invoke it

Are you sure this isn't being added by another plugin you have?
I'm trying to reproduce that on my computer and haven't been able to. Looking at the "Keyboard shortcuts" page in the [Obsidian Help Docs](https://help.obsidian.md/How+to/Keyboard+shortcuts), the only command that uses the `g` character is the "Graph View". 
I'm working on a Mac so I don't know if it's OS dependent.

**Comment by soticoker** [comment] 2021-09-13 16:06
> > it's a built in Obsidian function. The default hotkey is ctrl+g to invoke it
> 
> Are you sure this isn't being added by another plugin you have?
> I'm trying to reproduce that on my computer and haven't been able to. Looking at the "Keyboard shortcuts" page in the [Obsidian Help Docs](https://help.obsidian.md/How+to/Keyboard+shortcuts), the only command that uses the `g` character is the "Graph View". 
> I'm working on a Mac so I don't know if it's OS dependent.



Oh yeah, my bad!
I also use VS Code so mapped the same shortcut to Obsidian. By default, I don't think it has a shortcut mapped.

If you go in Obsidian - settings - hot keys, you can search for "go to line" & see what's up. Not at my pc at the mo' so can't find out what default was.

**Comment by spslater** [comment] 2021-09-13 20:41
I'm guessing you have the [Go To Line](https://github.com/phibr0/obsidian-go-to-line) plugin installed which would be why I am not seeing it! But I will look into the best way to work with this! I don't want to just do the same work here (especially with such a basic plugin). 

I'm gonna have to research if there is a way to hook into their plugin / check if their plugin is installed or something. I have the most of the functionality working already! So once I get that worked out it'll be up quickly after that!

**Comment by soticoker** [comment] 2021-09-14 14:48
Hi Sean, 
Apologies again, yep you're right about the 'Go To Line' plugin.  It's such a ubiquitous function I totally forgot it was 3rd party.  
Sure, like you said, which ever way is easiest/makes most sense for you to incorporate the new functionality sounds like a plan.   
Looking forward to trying it out !

**Comment by spslater** [comment] 2021-09-18 15:38
After taking to the maintainer of the [Go To Line](https://github.com/phibr0/obsidian-go-to-line) plugin, I decided to make the changes in that plugin instead. It keeps each plugin to one specific task and, like I said before, I don't want to just duplicate their work in this plugin. 

I'm going to be closing this issue because the functionality requested will be added [in this pull request](https://github.com/phibr0/obsidian-go-to-line/pull/2).

**Closed by spslater** 2021-09-18 15:38 UTC
Labels: enhancement

**Comment by soticoker** [comment] 2021-09-18 18:58
Makes sense, thanks for helping with this.
